services:
  todolist:
    image: mysql
    container_name: todolist
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=temp
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=Todolist
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"