version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_DATABASE: Todolist
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"